### ISSUE TITLE
Siamese Network Image Pairs

### ISSUE THREAD

**Issue by lazy-coder-1** [PacktPublishing/Hands-On-One-shot-Learning-with-Python#1]
How is "n" variable used to create image pairs in the Siamese Network ?

**Comment by gaurav-packt** [comment]
Hello,

The response shared by the author is as follows:

n is the minimum size of all the category images. Say for the MNIST dataset, we have the least  '1' number data points. we did this to ensure our data is equally distributed and wouldn't be biased towards one category. Following that we create pairs as shown in the code snippet at the following link:
![Explain](https://user-images.githubusercontent.com/35489117/96088738-7ea46480-0ee3-11eb-832a-4f9061875c36.PNG)

Hope this helps.
